export const UPDATE_DISABLED = 'UPDATE_DISABLED'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const UPDATE_WORKSHEET = 'UPDATE_WORKSHEET'
export const UPDATE_WORKSHEET_FORMDATA = 'UPDATE_WORKSHEET_FORMDATA'
export const SET_PHONE_EMAIL = 'SET_PHONE_EMAIL'
export const RESET_FORMDATA = 'RESET_FORMDATA'
export const UPDATE_FORMDATA_OTHER = 'UPDATE_FORMDATA_OTHER'

